version: '3'
services:
  db:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
    logging:
      driver: awslogs
      options:
        awslogs-group: EventManagement_db
        awslogs-region: ap-northeast-1
        awslogs-stream-prefix: mariadb

  web:
    image: 198606590602.dkr.ecr.ap-northeast-1.amazonaws.com/event-management_web:latest
    environment:
      - valueFrom: "Event-Management-DB-URL"
        name: DATABASE_URL
    build: .
    ports:
      - "80:80"
    depends_on:
      - db
    tty: true
    stdin_open: true
    command: bundle exec rails s -p 80 -b '0.0.0.0'
    logging:
      driver: awslogs
      options:
        awslogs-group: EventManagement_web
        awslogs-region: ap-northeast-1
        awslogs-stream-prefix: Event-management_web
