version: '3'
services:
  db:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
    logging:
      driver: awslogs
      options:
        awslogs-group: EventManagement_db
        awslogs-region: ap-northeast-1
        awslogs-stream-prefix: mariadb

  web:
    image: 198606590602.dkr.ecr.ap-northeast-1.amazonaws.com/event-management_web:latest
    # build: .
    # command: bundle exec rails s -p 3000 -b '0.0.0.0'
    ports:
      - "3000:3000"
    depends_on:
      - db
    tty: true
    stdin_open: true
    logging:
      driver: awslogs
      options:
        awslogs-group: EventManagement_web
        awslogs-region: ap-northeast-1
        awslogs-stream-prefix: Event-management_web
