version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout

      # - run:
      #       name: docker-compose up
      #       command: |
      #         docker-compose up -d

      - run:
            name: wait
            command: |
              export TEST_VALUE
              printenv TEST_VALUE

      - run:
            name: docker-compose run web rails db:create
            command: |
              docker-compose run web rails db:create
              docker-compose run web rails db:migrate


