version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout

      - run:
            name: docker-compose up
            command: |
              docker-compose up -d

      - run:
            name: docker-compose run web rails db:create
            command: |
              docker-compose run web rails db:create
              docker-compose run web rails db:migrate
            environment: |
              MYSQL_PASSWORD: <%= ENV['MYSQL_PASSWORD'] %>
              MYSQL_UESR: <%= ENV['MYSQL_UESR'] %>
