version: 2
jobs:
  build:
    working_directory: ~/event-management
    docker:
      - image: nozomi911/event-management:0.1
      - image: circleci/mariadb
        environment:
          MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}

    steps:
      - type: shell
        pwd: /
        shell: /bin/ash --login
        command: |
          rm /bin/sh
          ln -s /bin/ash /bin/sh
          echo $HOME
          ls -alh /bin
          which /bin/sh
          which /bin/ash
          echo $PATH
          export PATH="$PATH:~/.yarn/bin"

      - checkout

      - run:
          name: Install Docker Compose
          command: |
            curl -L https://github.com/docker/compose/releases/download/1.19.0/docker-compose-`uname -s`-`uname -m` > ~/docker-compose
            chmod +x ~/docker-compose
            sudo mv ~/docker-compose /usr/local/bin/docker-compose

      - setup_remote_docker

      - run:
          name: Build
          command: |
            ash entrypoint.sh

      - run:
          name: docker-compose up
          command: docker-compose up -d


      - run:
          name: sleep for waiting launch db
          command: sleep 1

      - run:
          name: "before_test: setup db"
          command: docker-compose run web rails db:create db:migrate

      - run:
          name: "before_test: setup db"
          command: docker-compose run web bundle exec rspec
