version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout:

      - run:
            name: environment test

            command: echo $ENV_FILE | base64 --decode > .env


      # - run:
      #       name: docker-compose up
      #       command: |
      #         docker-compose up -d

      # - run:
      #       name: docker-compose run web rails db:create
      #       environment:
      #         MYSQL_PASSWORD: "test"
      #         MYSQL_UESR: "test"
      #       command: |
      #         docker-compose run web rails db:create
      #         docker-compose run web rails db:migrate
