version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.4.1-node-browsers
    working_directory: ~/event-management

    steps:
      - checkout

      - run:
          name: execute hello world
          command: |
            echo 'hello world'
