version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout

      - run:
            name: docker-compose up
            command: |
              docker-compose up -d
              docker-compose run web rails db:create
              docker-compose run web rails db:migrate
