version: 2
jobs:
  build:
    docker:
      - image: nozomi911/event-management:0.1
      - image: mariadb
        environment:
          MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}

    working_directory: ~/event-management

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "Gemfile.lock" }}
            - v1-dependencies-

      - run:
          name: install dependencies
          command: |
            bundle install --jobs=4 --retry=3 --path vendor/bundle
      - save_cache:
          paths:
            - ./vendor/bundle
          key: v1-dependencies-{{ checksum "Gemfile.lock" }}

      - run: bundle exec rake db:create

