version: 2
jobs:
  build:
    docker:
      - image: nozomi911/event-management:0.1
      - image: circleci/mariadb:latest
        environment:
          MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
    working_directory: ~/event-management

    steps:
      - checkout

      - setup_remote_docker:
          docker_layer_caching: true

      - run:
          name: Install Docker client
          command: |
            set -x
            VER="17.03.0-ce"
            curl -L -o /tmp/docker-$VER.tgz https://download.docker.com/linux/static/stable/x86_64/docker-$VER.tgz
            tar -xz -C /tmp -f /tmp/docker-$VER.tgz
            mv /tmp/docker/* /usr/bin

      - run:
          name: Install Docker Compose
          command: |
            curl -L https://github.com/docker/compose/releases/download/1.19.0/docker-compose-`uname -s`-`uname -m` > ~/docker-compose
            chmod +x ~/docker-compose
            sudo mv ~/docker-compose /usr/local/bin/docker-compose


      - run:
          name: Build
          command: docker-compose build


      - run:
          name: Build
          command: docker-compose up -d

      - run:
          name: "before_test: setup db"
          command: docker-compose run web rails db:create db:migrate

      - run:
          name: "before_test: setup db"
          command: docker-compose run web bundle exec rspec
