version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout:
      - run:
            name: docker-compose up
            command: |
              echo $ENV_FILE | base64 --decode > .env
              docker-compose up -d
              sleep 1m
              docker-compose run web rails db:create
              docker-compose run web rails db:migrate
              docker-compose run web bundle exec rspec
